"""empty message

Revision ID: 79948d19ceaa
Revises: e7fb7dfb1c31
Create Date: 2024-07-28 22:17:52.027216

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '79948d19ceaa'
down_revision: Union[str, None] = 'e7fb7dfb1c31'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('categories', sa.Column('parent_id', sa.UUID(), nullable=True))
    op.drop_constraint('categories_parent_category_id_fkey', 'categories', type_='foreignkey')
    op.create_foreign_key(None, 'categories', 'categories', ['parent_id'], ['id'], ondelete='SET NULL')
    op.drop_column('categories', 'parent_category_id')
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('categories', sa.Column('parent_category_id', sa.UUID(), autoincrement=False, nullable=True))
    op.drop_constraint(None, 'categories', type_='foreignkey')
    op.create_foreign_key('categories_parent_category_id_fkey', 'categories', 'categories', ['parent_category_id'], ['id'], ondelete='SET NULL')
    op.drop_column('categories', 'parent_id')
    # ### end Alembic commands ###
