"""01

Revision ID: dab866c91b65
Revises: 70d43cebf759
Create Date: 2024-02-19 21:47:47.566897

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = 'dab866c91b65'
down_revision: Union[str, None] = '70d43cebf759'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('profiles', sa.Column('utc_offset', sa.Integer(), nullable=False))
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('profiles', 'utc_offset')
    # ### end Alembic commands ###
