"""empty message

Revision ID: e7fb7dfb1c31
Revises: 3a372c39a78b
Create Date: 2024-07-28 01:05:36.880396

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = 'e7fb7dfb1c31'
down_revision: Union[str, None] = '3a372c39a78b'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('categories', sa.Column('parent_category_id', sa.UUID(), nullable=True))
    op.create_foreign_key(None, 'categories', 'categories', ['parent_category_id'], ['id'], ondelete='SET NULL')
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_constraint(None, 'categories', type_='foreignkey')
    op.drop_column('categories', 'parent_category_id')
    # ### end Alembic commands ###
